In [1]:
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)

print(f'Dimensi feature: {X.shape}')
print(f'Class: {set(y)}')

Dimensi feature: (150, 4)
Class: {0, 1, 2}

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [4]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=0)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [5]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

In [6]:
import pandas as pd
import numpy as np
import sklearn.tree as tree
import sklearn.model_selection as ms
import sklearn.ensemble as ens
import sklearn.metrics as met

rf = ens.RandomForestClassifier(n_estimators=100)

In [7]:
data = pd.read_csv('/content/adult_data.csv')

In [8]:
data.head(10)

,age,workclass,fnlwft,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours-per-week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K

In [9]:
data.dropna(inplace=True)

In [10]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()

In [17]:
data['sex'] = enc.fit_transform(data['sex'].values)
data['education'] = enc.fit_transform(data['education'].values)
data['race'] = enc.fit_transform(data['race'].values)
data['marital_status'] = enc.fit_transform(data['marital_status'].values)
data['workclass'] = enc.fit_transform(data['workclass'].values)
data['occupation'] = enc.fit_transform(data['occupation'].values)
data['relationship'] = enc.fit_transform(data['relationship'].values)
data['native_country'] = enc.fit_transform(data['native_country'].values)

In [15]:
X = data.drop(['fnlwft', 'workclass', 'education', 'marital_status',
               'occupation', 'relationship', 'race', 'sex', 'native_country', 'income'], axis = 1)

v = data['income']

In [18]:
data.head(10)

,age,workclass,fnlwft,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours-per-week,native_country,income
0,39,7,77516,9,13,4,1,1,4,1,2174,0,40,39,<=50K
1,50,6,83311,9,13,2,4,0,4,1,0,0,13,39,<=50K
2,38,4,215646,11,9,0,6,1,4,1,0,0,40,39,<=50K
3,53,4,234721,1,7,2,6,0,2,1,0,0,40,39,<=50K
4,28,4,338409,9,13,2,10,5,2,0,0,0,40,5,<=50K
5,37,4,284582,12,14,2,4,5,4,0,0,0,40,39,<=50K
6,49,4,160187,6,5,3,8,1,2,0,0,0,16,23,<=50K
7,52,6,209642,11,9,2,4,0,4,1,0,0,45,39,>50K
8,31,4,45781,12,14,4,10,1,4,0,14084,0,50,39,>50K
9,42,4,159449,9,13,2,4,0,4,1,5178,0,40,39,>50K

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       48842 non-null  int64
 2   fnlwft          48842 non-null  int64
 3   education       48842 non-null  int64
 4   education_num   48842 non-null  int64
 5   marital_status  48842 non-null  int64
 6   occupation      48842 non-null  int64
 7   relationship    48842 non-null  int64
 8   race            48842 non-null  int64
 9   sex             48842 non-null  int64
 10  capital_gain    48842 non-null  int64
 11  capital_loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native_country  48842 non-null  int64
 14  income          48842 non-null  object
dtypes: int64(14), object(1)
memory usage: 5.6+ MB

In [22]:
X_train, X_test, y_train, y_test = ms.train_test_split(X, y, test_size = 0.2)

ValueError: ignored

In [23]:
rf.fit(X_train, y_train)
y_prediksi = rf.predict(X_test)
print('akurasi = ', met.accuracy_score(y_test, y_prediksi))
print(met.classification_report(y_test, y_prediksi))
print(rf.feature_importances_)

akurasi =  0.9777777777777777
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

[0.11611185 0.02391316 0.4656143  0.39436068]